@Test public void canSetCauseWithInstanceCreatedWithExplicitThrowableConstructor(){
  Throwable cause=new Exception();
  AssumptionViolatedException e=new AssumptionViolatedException("invalid number",cause);
  assertThat(e.getCause(),is(cause));
}
