@Test public void mainErrorsImmediate(){
  PublishSubject<Integer> main=PublishSubject.create();
  final PublishSubject<Integer> inner=PublishSubject.create();
  TestObserver<Integer> to=main.concatMapEager(new Function<Integer,ObservableSource<Integer>>(){
    @Override public ObservableSource<Integer> apply(    Integer t){
      return inner;
    }
  }
).test();
  main.onNext(1);
  main.onNext(2);
  inner.onNext(2);
  to.assertValue(2);
  main.onError(new TestException("Forced failure"));
  assertFalse("inner has subscribers?",inner.hasObservers());
  inner.onNext(3);
  inner.onComplete();
  to.assertFailureAndMessage(TestException.class,"Forced failure",2);
}
