public void testRunFailure() throws Exception {
  JUnitCore runner=new JUnitCore();
  Result result=runner.run(FailureTest.class);
  assertEquals(1,result.getRunCount());
  assertEquals(1,result.getFailureCount());
  assertEquals(AssertionError.class,result.getFailures().get(0).getException().getClass());
}
