public void testErrorInAfterClass() throws Exception {
  run=false;
  JUnitCore core=new JUnitCore();
  Result result=core.run(ErrorInAfterClass.class);
  assertTrue(run);
  assertEquals(1,result.getFailureCount());
}
