@Test @Ignore("Observers can't throw") public void onErrorFailureWithUnsubscribeFailure(){
  Subscriber<String> subscriber=subscriberOnErrorFail();
  try {
    subscriber.onSubscribe(THROWING_DISPOSABLE);
    new SafeSubscriber<String>(subscriber).onError(new SafeSubscriberTestException("onError failure"));
    fail("expects exception to be thrown");
  }
 catch (  Exception e) {
    e.printStackTrace();
    assertTrue(e instanceof RuntimeException);
    assertEquals("Error occurred when trying to propagate error to Subscriber.onError and during unsubscription.",e.getMessage());
    Throwable e2=e.getCause();
    assertTrue(e2 instanceof CompositeException);
    List<Throwable> innerExceptions=((CompositeException)e2).getExceptions();
    assertEquals(3,innerExceptions.size());
    Throwable e3=innerExceptions.get(0);
    assertTrue(e3 instanceof SafeSubscriberTestException);
    assertEquals("onError failure",e3.getMessage());
    Throwable e4=innerExceptions.get(1);
    assertTrue(e4 instanceof SafeSubscriberTestException);
    assertEquals("onErrorFail",e4.getMessage());
    Throwable e5=innerExceptions.get(2);
    assertTrue(e5 instanceof SafeSubscriberTestException);
    assertEquals("failure from unsubscribe",e5.getMessage());
  }
}
