@Test public void onNextOnErrorFailure(){
  try {
    OBSERVER_ONNEXT_ONERROR_FAIL().onNext("one");
    fail("expects exception to be thrown");
  }
 catch (  Exception e) {
    e.printStackTrace();
    assertTrue(e instanceof SafeSubscriberTestException);
    assertEquals("onNextFail",e.getMessage());
  }
}
