@Test public void testFail() throws Exception {
  MyAsyncProcess ap=new MyAsyncProcess(createHConnection(),CONF);
  List<Put> puts=new ArrayList<>(1);
  Put p=createPut(1,false);
  puts.add(p);
  AsyncRequestFuture ars=ap.submit(null,DUMMY_TABLE,puts,false,null,true);
  Assert.assertEquals(0,puts.size());
  ars.waitUntilDone();
  verifyResult(ars,false);
  Assert.assertEquals(NB_RETRIES + 1,ap.callsCt.get());
  Assert.assertEquals(1,ars.getErrors().exceptions.size());
  Assert.assertTrue("was: " + ars.getErrors().exceptions.get(0),failure.equals(ars.getErrors().exceptions.get(0)));
  Assert.assertTrue("was: " + ars.getErrors().exceptions.get(0),failure.equals(ars.getErrors().exceptions.get(0)));
  Assert.assertEquals(1,ars.getFailedOperations().size());
  Assert.assertTrue("was: " + ars.getFailedOperations().get(0),p.equals(ars.getFailedOperations().get(0)));
}
