@Test public void testTakeWithErrorHappeningInOnNext(){
  Observable<Integer> w=Observable.fromIterable(Arrays.asList(1,2,3)).take(2).map(new Function<Integer,Integer>(){
    @Override public Integer apply(    Integer t1){
      throw new IllegalArgumentException("some error");
    }
  }
);
  Observer<Integer> observer=TestHelper.mockObserver();
  w.subscribe(observer);
  InOrder inOrder=inOrder(observer);
  inOrder.verify(observer,times(1)).onError(any(IllegalArgumentException.class));
  inOrder.verifyNoMoreInteractions();
}
