@Test public void testFailedPut() throws Exception {
  MyAsyncProcess ap=new MyAsyncProcess(createHConnection(),CONF);
  List<Put> puts=new ArrayList<>(2);
  puts.add(new Put(GOOD_ROW).addColumn(FAMILY,FAMILY,FAMILY));
  puts.add(new Put(BAD_ROW).addColumn(FAMILY,FAMILY,FAMILY));
  final int expectedSize=puts.size();
  AsyncRequestFuture arf=ap.submit(DUMMY_TABLE,puts);
  arf.waitUntilDone();
  assertError(arf,1);
  Object[] result=arf.getResults();
  assertEquals(expectedSize,result.length);
  assertEquals(Result.class,result[0].getClass());
  assertTrue(result[1] instanceof IOException);
  assertTrue(puts.isEmpty());
  assertActionsInProgress(arf);
}
